jena:
  modelName: biluFusionLocal.v2
  fusekiURI: http://localhost:3330/knowledge


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8861/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:6603/rizhaogongan
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    show-sql: true