jena:
  modelName: biluFusionDev.v2
  fusekiURI: http://172.19.9.110/knowledge

spring:
  datasource:
    url: jdbc:mysql://47.104.8.27/rizhaogongan
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    show-sql: true
jdbc:
  user: root
  password: 123456
  driverClass: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://47.104.8.27:6603/rizhaogongan