server:
  port: 8809
  servlet-path: /api

spring:
  application:
    name: miami-publish
  data:
    mongodb:
      uri: mongodb://tahiti:Qs7UDDUliY@47.104.8.27:27101/zhinengtiaojie
  datasource:
      url: jdbc:mysql://47.104.8.27:6603/rizhaogongan
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
engine:
  type: jena2gongan

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://47.95.96.227:8861/eureka/

miami:
  publish:
    mongodb:
      database: zhinengtiaojie
      collection:
        bilu: tiaojieDocInfo
    elasticsearch:
      host: http://192.168.177.201:9200,http://192.168.177.227:9200
      index: bilu
      type: doc
      batchSize: 1000
mongo:
  mongodburi: mongodb://tahiti:Qs7UDDUliY@47.104.8.27:27101/zhinengtiaojie
  mongodb: zhinengtiaojie
  docCollection: aj_basic