jena:
  modelName: biluProdFusion
  fusekiURI: http://miami-fuseki:3330/knowledge

spring:
  datasource:
    url: jdbc:mysql://miami-mysql:3306/miami
    username: miami
    password: miami
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  http://miami-springcloud-eureka:8861/eureka/