jena:
  modelName: biluDev
  fusekiURI: http://localhost:3330/knowledge


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8861/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://tahiti:Qs7UDDUliY@47.104.8.27:27101/zhinengtiaojie
  datasource:
    url: jdbc:mysql://localhost:6603/rizhaogongan
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #show_sql: true
        #format_sql: true
        #use_sql_comments: true
        generate_statistics: true

    show-sql: false

miami:
  publish:
    mongodb:
      database: zhinengtiaojie
      collection:
        bilu: docContainerinfo
    elasticsearch:
      host: http://localhost:9200
      index: bilutest
      type: doc
      batchSize: 1000

mongo:
  mongodburi: mongodb://tahiti:Qs7UDDUliY@47.104.8.27:27101/zhinengtiaojie
  mongodb: zhinengtiaojie
  docCollection: aj_basic

person:
  personurl: http://tahiti-api.test.richinfoai.com/api/v2/person/

jdbc:
  user: root
  password: 123456
  driverClass: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:6603/rizhaogongan

logging:
  level:
    org.hibernate.stat=debug
