jena:
  modelName: biluProdFusion
  fusekiURI: http://miami-fuseki:3330/knowledge

spring:
  datasource:
    url: jdbc:mysql://miami-mysql:3306/miami
    username: miami
    password: miami
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  data:
    mongodb:
      uri: mongodb://miami-mongodb:27017/biluProdRizhao

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone:  http://miami-springcloud-eureka:8861/eureka/

miami:
  publish:
    mongodb:
      database: biluProdRizhao
      collection:
        bilu: biluDocInfo
    elasticsearch:
      host: http://10.53.187.39:9200,http://10.53.187.40:9200,http://10.53.187.41:9200

mongo:
  mongodburi: mongodb://miami-mongodb:27017/biluProdRizhao
  mongodb: bihuan
  docCollection: aj_basic